

export  const FETCH_PORTFOLIOS = 'FETCH_PORTFOLIOS';
export  const FETCH_PORTFOLIOS_FAIL = 'FETCH_PORTFOLIOS_FAIL';
export const FETCH_PORTFOLIOS_INIT = 'FETCH_PORTFOLIOS_INIT';
export  const FETCH_TOOLS = 'FETCH_TOOLS';
export  const FETCH_TOOLS_FAIL = 'FETCH_TOOLS_FAIL';
export const FETCH_TOOLS_INIT = 'FETCH_TOOLS_INIT';
export  const FETCH_BLOGS = 'FETCH_BLOGS';
export  const FETCH_BLOGS_FAIL = 'FETCH_BLOGS_FAIL';
export const FETCH_BLOGS_INIT = 'FETCH_BLOGS_INIT';
export  const FETCH_BLOG_By_ID = 'FETCH_BLOG_By_ID';
export  const FETCH_BLOG_By_ID_INIT = 'FETCH_BLOG_By_ID_INIT';


export  const SEARCH_RENTALS = 'SEARCH_RENTALS';
export const FETCH_RENTALS_INIT = 'FETCH_RENTALS_INIT';
export  const FETCH_RENTAL_By_ID = 'FETCH_RENTAL_By_ID';
export  const FETCH_RENTAL_By_ID_INIT = 'FETCH_RENTAL_By_ID_INIT';
export  const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export  const LOGIN_FAILURE = 'LOGIN_FAILURE';
export  const LOGOUT = 'LOGOUT';
export  const FETCH_BOOKINGS_INIT = 'FETCH_BOOKINGS_INIT';
export  const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export  const FETCH_BOOKINGS_FAIL = 'FETCH_BOOKINGS_FAIL';
export  const UPDATE_RENTAL_FAIL = 'UPDATE_RENTAL_FAIL';
export  const UPDATE_RENTAL_SUCCESS = 'UPDATE_RENTAL_SUCCESS';
export  const RESET_ERRORS = 'RESET_ERRORS';